version: '3.8'

services:
  #api:
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - db
  #  environment:
  #    MONGODB_URI: mongodb://promptserver:password@localhost:27017/?retryWrites=true&w=majority
    postgres:
      image: postgres:16-alpine
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: promptserver
        POSTGRES_PASSWORD: password
        POSTGRES_DB: promptdb