version: '3.8'

services:
  #api:
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - db
  #  environment:
  #    MONGODB_URI: mongodb://promptserver:password@localhost:27017/?retryWrites=true&w=majority
    postgres:
      image: postgres:16-alpine
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: promptserver
        POSTGRES_PASSWORD: password
        POSTGRES_DB: promptdb
      volumes:
        - db-data:/Users/abhash/Desktop/gpt-4/bunlearn/hi-elysia/volumes/postgres
    elasticsearch:
      image: elasticsearch:7.17.13
      ports:
        - "9200:9200"
      environment:
        - discovery.type=single-node
        - ELASTIC_PASSWORD=password
        - xpack.security.enabled=false
        - bootstrap.memory_lock=true
      volumes:
        - search-data:/Users/abhash/Desktop/gpt-4/bunlearn/hi-elysia/volumes/elasticsearch

volumes:
  db-data:
  search-data:
