import { t } from 'elysia'
import { Static } from '@sinclair/typebox'
import { EVariable } from './shared'

/* request provides the following:
1. name of the context database
2. description of the context data
3. python script file - uploaded to shared S3 bucket
4. environment variables required by the python script

Then the generated VectorDatabase is referred via contextDBId
The data generated by the python script is stored in the dedicated rawDataLoc
*/

export const EInitContextRequest = t.Object({
	name: t.String(),
	desc: t.String(),
	script: t.File(
		{
			type: "text",
			maxSize: '1k',
		}
	),
	env: t.Array(EVariable),
})

export const EInitContextResponse = t.Object({
	id: t.Integer(),
	success: t.Boolean(),
	errorReason: t.Optional(t.String()),
})

export type InitContextRequest = Static<typeof EInitContextRequest>;
export type InitContextResponse = Static<typeof EInitContextResponse>;